### PR TITLE
Implement /applications page

### LINKED ISSUE #59: Implement page for viewing all of a user's applications to projects that they would like to join

### PR DESCRIPTION
**Pull request by mtso**
# Changes

- Implements `/applications` page to show list of user's Applications
- Implements `/applications/{id}` page to show an application and allow edits

# Testing

- Run app
- Go to `/applications`
- Test that search filters work
- Test that single app page allows requestedRole and message changes

Closes #59

### CODE REVIEW

**Comment by mtso** [comment]
Screen Shot 2022-03-10 at 9 49 23 PM
Screen Shot 2022-03-10 at 9 49 17 PM
Screen Shot 2022-03-10 at 9 48 57 PM

**Review by DanielLopezCS — APPROVED** [review]
Everything looks clean.

**Comment by seann1** [comment]
I was testing this by logging in with one account, applying to a project, logging in with my other account, rejecting the application, then logging back in with the first account, and I'm not seeing rejected applications showing up.

**Comment by mtso** [comment]
> I was testing this by logging in with one account, applying to a project, logging in with my other account, rejecting the application, then logging back in with the first account, and I'm not seeing rejected applications showing up.

Great catch, the status value when the application is rejected by the owner is actually `closed`, so I've updated it to `Closed` instead of `Rejected`

**Pull request merged**
